import './globals.css'
import { Inter } from 'next/font/google'


export const metadata = {
  title: 'Orebi_Mernian',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-primaryFont'>{children}</body>
    </html>
  )
}
